

import Foundation

var showpass = false
let AppName = "Registration Form"
let kImageSelect = "Plesae select the image"
let kpassword = "Plesae select valid password"
 let validPassword = "Enter valid password"
let requiredFilledAlert = "Please fill in the required fields"
let kClassSelected = "selected_class"
let selectQuaAlert = "Select qualification"
let kAlertFirstName = "Please enter your first name"
let kAlertValidEmail = "Please enter valid Email address"
let kAlertFullName = "Please enter your full name"
let kAlertLastName = "Please enter your last name"
let kAlertName = "Please enter your first name"
let kAlertMobile = "Please enter your mobile number"
let kAlertMobileValid = "Pls enter valid mobile number"
let kAlertMobilecharacter = "Please enter Maximum 10 number mobile number"
let kAlertEmail = "Please enter your Email address"
let pleaseEnterValidMobileNumber = "Please enter valid mobile number."
let pleaseEnterPassword = "Please enter password."
let pleaseconfirmPassword = "Please enter confirm password."
let pleaseEnterQualification = "Select your Qualification"
let pleaseEnteryear = "Select passing year"
let pleasegrade = "Please enter grade or percentage"
let Kalertexpe = "Please enter experience"
let Kalertdesign = "Select designation"
let Kaldomain = "Select domain"
let KalertAdress =  "Please enter Adress"
let validAdressland =  "Please enter Landmark"
let validLandMark = "Enter valid landmark"
let KalertLandstate =  "Please enter address, landmark and state"
let Kalertcity =  "Enter valid city"
let Kalertstate =  "Select your State"
let Kalertpin =  "Enter valid pincode"
let KalertpinsAlert =  "Enter pincode"
let submissiomAlet =  "Submission Successfully"
let validInput = "^[a-zA-Z0-9]+$"
let numRegex = ".*\\d.*"
let specialChra = ".*[^A-Za-z0-9].*"
let validationSuccessfull = "Validation successfull"
 let validPassingYear = "Enter valid passing year"
 let validGrade = "Enter valid grade"
let validdesignation  = "Enter valid designation"
 let entervalidyearsofexperience = "Enter valid years of experience"
let entervaliddomain = "Enter valid domain"
let confirmpassmatch = "password not matching"



